### ISSUE TITLE
Adding more checks?

### ISSUE THREAD

**Issue by allain** [alexbyk/panicif#1]
Would you be open to me adding more checks?

I'd be useful and more concise to write:

```golang
panicif.Nil(created, "created should not be nil")
panicif.NotNil(userMap, "expected userMap to be nil here but was %v", userMap)
```

The second one is arguably less useful than the first, but it's easier than groking the ones below:

```golang
panicif.False(userMap == nil, "...")
panicif.True(userMap != nil, "...")
```

If you're open to contributions I'll write the PR.

**Comment by alexbyk** [comment]
makes sense. Go ahead, pr is welcome
